apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  labels:
    app.kubernetes.io/name: ibmcloud-operators
  name: ibmcloud-operator
  namespace: ibmcloud-operators
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibmcloud-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ibmcloud-operator
    spec:
      containers:
      - args:
        - -logtostderr=true
        - -v=5
        command:
        - ./manager
        image: cloudoperators/ibmcloud-operator:0.1.1
        imagePullPolicy: Always
        name: ibmcloud-controllers
      serviceAccountName: ibmcloud-operator
