apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Service
metadata:
  name: myappid
spec:
  plan: lite
  serviceClass: appid
---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Binding
metadata:
  name: binding-appid
spec:
  serviceName: myappid