apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Service
metadata:
  name: mymessagehub
spec:
  plan: standard
  serviceClass: messagehub
---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Binding
metadata:
  name: binding-messagehub
spec:
  serviceName: mymessagehub
---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Topic
metadata:
  name: mytopic
spec:
  bindingFrom:
    name: binding-messagehub
  topicName: mytopic
  numPartitions: 3
  replicationFactor : 3
  configs :
    - name: retentionMs
      value: 2592000000