apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Topic
metadata:
  name: topic2
spec:
  bindingFrom:
    name: binding-messagehub
  topicName: exampleone
  numPartitions: 3
  replicationFactor : 3
  configs :
    - name: retentionMs
      value: 2592000000