apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Service
metadata:
  name: myappconnect
spec:
  plan: Lite
  serviceClass: AppConnect
  serviceClassType: CF
---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Binding
metadata:
  name: binding-appconnect
spec:
  serviceName: myappconnect