apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Service
metadata:
  name: mycloudant
spec:
  plan: lite
  serviceClass: cloudantnosqldb
---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Binding
metadata:
  name: binding-cloudant
spec:
  serviceName: mycloudant