apiVersion: ibmcloud.ibm.com/v1beta1
kind: Service
metadata:
  name: myes4
spec:
  plan: standard
  serviceClass: databases-for-elasticsearch
  parameters:
  - name: members_disk_allocation_mb
    value: 30720
  - name: members_memory_allocation_mb
    value: 6144
  - name: service-endpoints
    value: private
  - name: foo
    valueFrom:
      secretKeyRef:
        name: xyz
        key: apikey
